name: ctest
on: [ push, pull_request ]
jobs:
  validate:
    runs-on: ubuntu-23.10
    steps:
      - uses: actions/checkout@v2

      - name: build and test
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang
          mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-fsanitize=undefined,bounds,address" -DCMAKE_BUILD_TYPE=Debug .. && make && ctest
